{
 "title": "Status",
 "description": "We continuously monitor the status of UH-IaaS. If there are any interruptions in service, a note will be posted here.",
 "time": { "from": "now-7d", "to": "now-1m" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "domain", "query": "uh-iaas.no" }
  ]
 },
 "panels": [
  {
   "title": "api.$domain",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "stats.gauges.uh-iaas.bgo.checks.api"
    }
   ]
  },
  {
   "title": "access.$domain",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "stats.gauges.uh-iaas.bgo.checks.access"
    }
   ]
  },
  {
   "title": "dashboard.$domain",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "stats.gauges.uh-iaas.bgo.checks.dashboard"
    }
   ]
  },
  {
   "title": "docs.$domain",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "stats.gauges.uh-iaas.bgo.checks.docs"
    }
   ]
  },
  {
   "title": "Important",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "News",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instances",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(stats.gauges.uh-iaas.*.instances, 'stats\\.gauges\\.uh-iaas\\.([^\\.]+?)\\.instances', '\\1')"
    }
   ]
  },
  {
   "title": "Projects and Users",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.uh-iaas.bgo.{projects,users}, 4)"
    }
   ]
  }
 ]
}