---
# NVIDIA SR-IOV-based vGPU hosts need SR-IOV enabled and mdevs created
include:
  kickstart:
    - profile::openstack::compute::pci_passthrough
    - profile::openstack::compute::nvidia_vgpu_createmdev
  default:
    - nova::compute::mdev
    - profile::openstack::compute::pci_passthrough
    - profile::openstack::compute::nvidia_vgpu_createmdev

#FIXME:el9 move to common after all computes are el9 with zed
openstack_version: "zed"

# Configure network
named_interfaces::config:
  mgmt:
  - em1
  trp:
  - bond0
  live:
  - bond0.120

profile::base::network::nm_network_auto_bonding:
  trp:
    p8p1:
      ethernet:
        'mtu': '9000' # the MTU size must be set also on the slave interfaces
    p8p2:
      ethernet:
        'mtu': '9000'

# Enable extra yum repo vGPU drivers
profile::base::yumrepo::repo_hash:
  nrec-nonfree:
    ensure: present

# NVIDIA SR-IOV-based vGPU hosts need sriov-manage at boot before mdev creation
profile::openstack::compute::nvidia_vgpu_createmdev::enable: true
profile::base::selinux::semodules:
  sriov_manage:
    avc_file:   'sriov_manage.avc'

# Configure storage
profile::base::lvm::physical_volume:
  '/dev/nvme0n1p4':
    ensure: present
    force:  true
  '/dev/sda':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_instances':
    physical_volumes:
      - /dev/sda
  'vg_ext':
    physical_volumes:
      - /dev/nvme0n1p4
profile::base::lvm::logical_volume:
  'lv_instances':
    volume_group: 'vg_instances'
    fs_type:      "xfs"
    mountpath:    "/var/lib/nova/instances"

# Install GPU driver
profile::base::common::packages:
  'wget': {}
  'kernel-devel': {}
  'kernel-headers': {}
  'unzip': {}
  'NVIDIA-vGPU-rhel': {}

# Configure GPU
# NVIDIA L40S partitioned into 1x vGPUs, with CUDA support
#
# From "mdevctl types":
#
#  nvidia-1155
#    Available instances: 1
#    Device API: vfio-pci
#    Name: NVIDIA L40S-24Q
#    Description: num_heads=4, frl_config=60, framebuffer=24576M, max_resolution=7680x4320, max_instance=2
#
nova::compute::mdev::mdev_types:
  nvidia-1155: {}

# Max 8 instances per host
nova::scheduler::filter::max_instances_per_host: '8'

# NVIDIA newer generation cards need SR-IOV
profile::openstack::compute::pci_passthrough::configure_intel_iommu: true

# FIXME: remove when telemetry/ceilometer is up in all environments and move to common
profile::openstack::compute::manage_telemetry: true

# Blacklist the open source GPU driver
profile::base::physical::blacklist_drv: true
profile::base::physical::blacklist_drv_list:
  'nouveau': {}

# Configure CPU
# FIXME: We want to have only SapphireRapids once all hodsts run EL9 and all VMs run on EL9 hosts
nova::compute::libvirt::cpu_models: ['SapphireRapids','Broadwell-noTSX-IBRS']
# Set extra cpu flags:
# * -hle, -rtm: disable TSX for all cpu_models. Kernel has disabled TSX (hle and rtm) as a security mitigation for the TAA vulnerability
# * vmx: Enable nested virtualization support
nova::compute::libvirt::cpu_model_extra_flags: ['vmx', '-hle', '-rtm']

# These compute hosts use local storage for instances
nova::compute::rbd::ephemeral_storage: false
nova::compute::libvirt::images_type: 'default'

# Configuration items not explicitly supported by the Puppet module
nova::config::nova_config:
  DEFAULT/metadata_workers:
    value: '4'
