---
include:
  default:
    - profile::openstack::compute::pci_passthrough
    - profile::openstack::compute::nvidia_vgpu_createmdev

#FIXME:el9 move to common after all computes are el9 with zed
openstack_version: "zed"

# Configure network
named_interfaces::config:
  mgmt:
  - em3
  trp:
  - bond0
  live:
  - bond0.120

profile::base::network::nm_network_auto_bonding:
  trp:
    p3p1:
      ethernet:
        'mtu': '9000' # the MTU size must be set also on the slave interfaces
    p3p2:
      ethernet:
        'mtu': '9000'

# Enable extra yum repo vGPU drivers
profile::base::yumrepo::repo_hash:
  nrec-nonfree:
    ensure: present

# NVIDIA SR-IOV-based vGPU hosts need sriov-manage at boot before mdev creation
profile::openstack::compute::nvidia_vgpu_createmdev::enable: true
profile::base::selinux::semodules:
  sriov_manage:
    avc_file:   'sriov_manage.avc'

# Configure storage
profile::base::lvm::physical_volume:
  '/dev/sda4':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_ext':
    physical_volumes:
      - '/dev/sda4'
profile::base::lvm::logical_volume:
  'lv_instances':
    volume_group: 'vg_ext'
    fs_type:      "xfs"
    mountpath:    "/var/lib/nova/instances"

# Nova overrides
nova::cpu_allocation_ratio:  '4'
nova::disk_allocation_ratio: '1'
nova::ram_allocation_ratio:  '1'

# Install GPU driver
profile::base::common::packages:
  'wget': {}
  'kernel-devel': {}
  'kernel-headers': {}
  'mdevctl': {}
  'unzip': {}
#  'NVIDIA-vGPU-rhel': {} # use runfile instead, until a package for el9.8 is available

# Configure GPU
# TODO
# NVIDIA Quadro RTX partitioned into 2 x vGPUs, with CUDA support
#
# From "mdevctl types":
#
#  nvidia-381
#    Available instances: 2
#    Device API: vfio-pci
#    Name: GRID RTX6000P-12Q
#    Description: num_heads=4, frl_config=60, framebuffer=12288M, max_resolution=7680x4320, max_instance=2
#
nova::compute::mdev::mdev_types:
  nvidia-381: {}

# Max 6 instances per host
nova::scheduler::filter::max_instances_per_host: '6'

# NVIDIA newer generation cards need SR-IOV
profile::openstack::compute::pci_passthrough::configure_intel_iommu: true

# FIXME: remove when telemetry/ceilometer is up in all environments and move to common
profile::openstack::compute::manage_telemetry: true

# Blacklist the open source GPU driver
profile::base::physical::blacklist_drv: true
profile::base::physical::blacklist_drv_list:
  'nouveau': {}

nova::compute::libvirt::cpu_models: ['Cascadelake-Server-noTSX']

# These compute hosts use local storage for instances
nova::compute::rbd::ephemeral_storage: false
nova::compute::libvirt::images_type: 'default'

# Configuration items not explicitly supported by the Puppet module
nova::config::nova_config:
  DEFAULT/metadata_workers:
    value: '4'

