HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html


<html>
<body>
<h1>Be Right Back</h1>
Sorry, we're down at the moment
<br>
<a href="http://status.iaas.uib.no">http://status.iaas.uib.no</a>
</body>
</html>
