---
named_interfaces::config:
  mgmt:
    - em1
  trp:
    - bond1
  live:
    - bond1.120

profile::base::network::nm_network_auto_bonding:
  trp:
    em3:
      ethernet:
        'mtu': '9000' # the MTU size must be set also on the slave interfaces
    em4:
      ethernet:
        'mtu': '9000'

# cpu module used by kvm (default is to disable nested virtualization)
profile::virtualization::nested::module: 'kvm_amd'
profile::virtualization::nested::value:  '0'

# Sensu
sensu::agent::annotations:
  'disk_warning': '90'
  'disk_critical': '95'
  'cpu_warning': '95'
  'cpu_critical': '100'

# Nova overrides
nova::compute::libvirt::cpu_models:              ['EPYC']
nova::cpu_allocation_ratio:                      '8'
nova::disk_allocation_ratio:                     '1'
nova::ram_allocation_ratio:                      '1.2'
nova::scheduler::filter::max_instances_per_host: '20'

# Create and enable more swap
profile::base::common::extraswap:        true
profile::base::common::extraswap_sizegb: 30

profile::base::lvm::physical_volume:
  '/dev/sdb':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_swap':
    physical_volumes:
      - /dev/sda4
  'vg_ext':
    physical_volumes:
      - /dev/sdb
profile::base::lvm::logical_volume:
  'lv_swap2':
    volume_group: 'vg_swap'
    fs_type:      xfs
    mountpath:    "/var/lib/swap"
  'lv_instances':
    volume_group: 'vg_ext'
    fs_type:      "xfs"
    mountpath:    "/var/lib/nova/instances"

# These compute host uses local storage for instances
nova::compute::rbd::ephemeral_storage: false

# Configuration items not explicitly supported by the Puppet module
nova::config::nova_config:
  DEFAULT/metadata_workers:
    value: '2'

nova::compute::libvirt::images_type: 'default'
