---
include:
  default:
    - profile::openstack::openrc
    - profile::application::himlarcli
    - profile::application::himlarservice
    - profile::development::network::dns
    - profile::network::services
    - profile::network::nat
    - profile::application::rngd
    - profile::monitoring::telegraf


named_interfaces::config:
  mgmt:
    - eth0
  trp:
    - eth1
  public:
    - dummy0

profile::application::rngd::enable: true

profile::base::common::packages:
  'python2-openstackclient': {} # FIXME remove when all proxies are el8
  'python3-openstackclient': {}
  'python3-designateclient': {}
  'bash-completion': {}
  'bash-completion-extras': {}  # FIXME remove when all proxies are el8
  'jq': {}
  'python2-gnocchiclient': {}   # FIXME remove when all proxies are el8
  'python3-gnocchiclient': {}
  'python2-osc-placement': {}   # FIXME remove when all proxies are el
  'python3-osc-placement': {}
  'openstack-selinux': {}
  'rsyslog': { ensure: present } # nice to have
  'git': {}
  'gcc': {}
  'openldap-devel': {}
  'openssl-devel': {}
  'libffi-devel': {}
  'python3.11': {} # needed by himlarservice

profile::network::services::firewall_extras:
  source: '%{network_mgmt1}/%{netmask_mgmt1}'

profile::network::interface::create_custom_routes: true # New interface class needs enabling
profile::network::services::dns_proxy:             true
profile::network::services::http_proxy:            true
profile::development::network::dns::manage_hosts:  true
profile::development::network::dns::use_dnsmasq:   true
profile::base::network::manage_dummy:              true # FIXME remove when all proxies are migrated to el8
profile::network::interface::manage_dummy:         true
profile::network::nat::enable_snat:                true
profile::network::nat::source:                     "%{::network_mgmt1}/%{::netmask_mgmt1}"
profile::network::nat::outiface:                   'eth1'
profile::application::himlarservice::package_url:  'https://download.iaas.uio.no/nrec/rpm/himlarservice-2.0-1.el8.x86_64.rpm'
profile::application::himlarservice::enable:       true

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
  epel: # should be absent when using RDO, but whitelist can also work
    ensure:   present
    includepkgs: 'tinyproxy htop bash-completion-extras privoxy' # FIXME: Remove tinyproxy when el7 is gone
  calico%{hiera('calico_version')}:
    ensure: present
    includepkgs: 'dnsmasq'
  influxdb:
     ensure: present

logrotate::rules:
  himlarcli:
    path:           ['/opt/himlarcli/logs/himlar.log']
    rotate:         4
    size:           '100M'
    dateext:        true
    missingok:      true
    compress:       true

# telegraf
#profile::monitoring::telegraf::enable_telegraf:     true
openstack_influxdb_bucket: "openstack"

profile::monitoring::telegraf::outputs:
  influxdb_v2:
    options:
      - urls: ["https://%{hiera('mgmt__address__influx')}:8086"]
        tls_ca: '/etc/puppetlabs/puppet/ssl/certs/ca.pem'
        token: "%{hiera('influxdb_admin_token')}"
        organization: "%{hiera('profile::monitoring::influxdb::org')}"
        bucket: "%{hiera('openstack_influxdb_bucket')}"
        insecure_skip_verify: true
        tagpass:
          bucket: ["%{hiera('openstack_influxdb_bucket')}"]

profile::monitoring::telegraf::inputs:
  socket_listener:
    ensure: absent
  openstack:
    options:
      - authentication_endpoint: "%{hiera('endpoint__identity__public')}"
        interval:   '10m'
        username:   'admin'
        password:   "%{hiera('keystone_admin_password')}"
        #domain:     'Default'
        project:    "%{hiera('keystone__admin__project')}"
        enabled_services:
          #- 'servers'
          #- 'storage_pools'
          - 'projects'
          - 'hypervisors'
          #- 'subnets'
          #- 'aggregates'
          #- 'flavors'
          #- 'networks'
          #- 'volumes'
        tagexclude:    ["cpu_*"]
        fieldexclude:  ["cpu_*"]
#        tag_prefix: "openstack_tag_"
#        tag_value:  true
        tags:
          bucket: "%{hiera('openstack_influxdb_bucket')}"


# sensu
sensu::agent::subscriptions:
  - 'base'
  - 'nodes'
  - 'metrics'
  - 'proxy'

# FIXME:sensu-go
profile::monitoring::sensu::agent::enable_go_agent:   true
profile::monitoring::sensu::agent::enable_agent:      false
