---
profile::openstack::resource::host_aggregate:
  group1:
    availability_zone: "%{::location}-default-1"
    filter_hosts: true # will not fail if host does not yet exist
    hosts:
      - "%{::location}-compute-01.%{hiera('domain_mgmt')}"
  group2:
    availability_zone: "%{::location}-default-1"
  group3:
    availability_zone: "%{::location}-default-1"
  windows1:
    availability_zone: "%{::location}-default-1"
    metadata:
      type: 'windows'

profile::base::common::packages:
  'python3-redis': {} # OSProfiler dependency

profile::openstack::novactrl::manage_osprofiler: true

# FIXME: temp fix to be able to create the aggregates with puppet
keystone::bootstrap::username:              'admin'
keystone::bootstrap::password:              "%{hiera('keystone_admin_password')}"
keystone::bootstrap::project_name:          "%{hiera('keystone__admin__project')}"
