---
include:
  default:
    - profile::storage::cephclient

profile::storage::cephclient::enable: true

ceph::profile::params::client_keys:
  'client.admin':
    secret: "%{hiera('ceph_storage_client_admin_key')}"
    mode: '0600'
    user: 'ceph'
    group: 'ceph'
    cap_mon: 'allow *'
    cap_osd: 'allow *'
    cap_mds: 'allow *'

profile::openstack::metric::manage_storage_file: false
profile::openstack::metric::manage_storage_ceph: true
profile::openstack::metric::manage_storage_incoming_redis: true
profile::openstack::metric::manage_redis: true

# Override LVM disks
profile::base::common::manage_lvm: false
