---
profile::monitoring::sensu::agent::enable_go_agent:     false #FIXME

network::default_interfaces_hash:
  DEVICE_METADATA:
    localhost:
      hwsku: DS1000
      platform: x86_64-cel_ds1000-r0
      hostname: "%{::verified_certname}"
      timezone: "%{hiera('timezone::timezone')}"
      type: MgmtTsToR
  BREAKOUT_CFG:
    Ethernet0:
      brkout_mode: 1x1000[100,10]
    Ethernet1:
      brkout_mode: 1x1000[100,10]
    Ethernet2:
      brkout_mode: 1x1000[100,10]
    Ethernet3:
      brkout_mode: 1x1000[100,10]
    Ethernet4:
      brkout_mode: 1x1000[100,10]
    Ethernet5:
      brkout_mode: 1x1000[100,10]
    Ethernet6:
      brkout_mode: 1x1000[100,10]
    Ethernet7:
      brkout_mode: 1x1000[100,10]
    Ethernet8:
      brkout_mode: 1x1000[100,10]
    Ethernet9:
      brkout_mode: 1x1000[100,10]
    Ethernet10:
      brkout_mode: 1x1000[100,10]
    Ethernet11:
      brkout_mode: 1x1000[100,10]
    Ethernet12:
      brkout_mode: 1x1000[100,10]
    Ethernet13:
      brkout_mode: 1x1000[100,10]
    Ethernet14:
      brkout_mode: 1x1000[100,10]
    Ethernet15:
      brkout_mode: 1x1000[100,10]
    Ethernet16:
      brkout_mode: 1x1000[100,10]
    Ethernet17:
      brkout_mode: 1x1000[100,10]
    Ethernet18:
      brkout_mode: 1x1000[100,10]
    Ethernet19:
      brkout_mode: 1x1000[100,10]
    Ethernet20:
      brkout_mode: 1x1000[100,10]
    Ethernet21:
      brkout_mode: 1x1000[100,10]
    Ethernet22:
      brkout_mode: 1x1000[100,10]
    Ethernet23:
      brkout_mode: 1x1000[100,10]
    Ethernet24:
      brkout_mode: 1x1000[100,10]
    Ethernet25:
      brkout_mode: 1x1000[100,10]
    Ethernet26:
      brkout_mode: 1x1000[100,10]
    Ethernet27:
      brkout_mode: 1x1000[100,10]
    Ethernet28:
      brkout_mode: 1x1000[100,10]
    Ethernet29:
      brkout_mode: 1x1000[100,10]
    Ethernet30:
      brkout_mode: 1x1000[100,10]
    Ethernet31:
      brkout_mode: 1x1000[100,10]
    Ethernet32:
      brkout_mode: 1x1000[100,10]
    Ethernet33:
      brkout_mode: 1x1000[100,10]
    Ethernet34:
      brkout_mode: 1x1000[100,10]
    Ethernet35:
      brkout_mode: 1x1000[100,10]
    Ethernet36:
      brkout_mode: 1x1000[100,10]
    Ethernet37:
      brkout_mode: 1x1000[100,10]
    Ethernet38:
      brkout_mode: 1x1000[100,10]
    Ethernet39:
      brkout_mode: 1x1000[100,10]
    Ethernet40:
      brkout_mode: 1x1000[100,10]
    Ethernet41:
      brkout_mode: 1x1000[100,10]
    Ethernet42:
      brkout_mode: 1x1000[100,10]
    Ethernet43:
      brkout_mode: 1x1000[100,10]
    Ethernet44:
      brkout_mode: 1x1000[100,10]
    Ethernet45:
      brkout_mode: 1x1000[100,10]
    Ethernet46:
      brkout_mode: 1x1000[100,10]
    Ethernet47:
      brkout_mode: 1x1000[100,10]
    Ethernet48:
      brkout_mode: 1x10G[1G]
    Ethernet49:
      brkout_mode: 1x10G[1G]
    Ethernet50:
      brkout_mode: 1x10G[1G]
    Ethernet51:
      brkout_mode: 1x10G[1G]
    Ethernet52:
      brkout_mode: 1x10G[1G]
    Ethernet53:
      brkout_mode: 1x10G[1G]
    Ethernet54:
      brkout_mode: 1x10G[1G]
    Ethernet55:
      brkout_mode: 1x10G[1G]
  DNS_NAMESERVER:
    "%{hiera('netcfg_dns_mgmt_server1')}": {}
    "%{hiera('netcfg_dns_mgmt_server2')}": {}
  MGMT_VRF_CONFIG:
    vrf_global:
      mgmtVrfEnabled: 'true'
  NTP:
    global:
      vrf: mgmt
  NTP_SERVER:
    172.16.0.126: {}
    172.16.0.127: {}
  PORT:
    Ethernet0:
      admin_status: up
      alias: Eth1/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '1'
      lanes: '26'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet1:
      admin_status: up
      alias: Eth2/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '2'
      lanes: '25'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet2:
      admin_status: up
      alias: Eth3/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '3'
      lanes: '28'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet3:
      admin_status: up
      alias: Eth4/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '4'
      lanes: '27'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet4:
      admin_status: up
      alias: Eth5/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '5'
      lanes: '30'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet5:
      admin_status: up
      alias: Eth6/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '6'
      lanes: '29'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet6:
      admin_status: up
      alias: Eth7/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '7'
      lanes: '32'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet7:
      admin_status: up
      alias: Eth8/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '8'
      lanes: '31'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet8:
      admin_status: up
      alias: Eth9/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '9'
      lanes: '34'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet9:
      admin_status: up
      alias: Eth10/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '10'
      lanes: '33'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet10:
      admin_status: up
      alias: Eth11/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '11'
      lanes: '36'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet11:
      admin_status: up
      alias: Eth12/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '12'
      lanes: '35'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet12:
      admin_status: up
      alias: Eth13/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '13'
      lanes: '38'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet13:
      admin_status: up
      alias: Eth14/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '14'
      lanes: '37'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet14:
      admin_status: up
      alias: Eth15/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '15'
      lanes: '40'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet15:
      admin_status: up
      alias: Eth16/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '16'
      lanes: '39'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet16:
      admin_status: up
      alias: Eth17/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '17'
      lanes: '42'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet17:
      admin_status: up
      alias: Eth18/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '18'
      lanes: '41'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet18:
      admin_status: up
      alias: Eth19/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '19'
      lanes: '44'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet19:
      admin_status: up
      alias: Eth20/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '20'
      lanes: '43'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet20:
      admin_status: up
      alias: Eth21/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '21'
      lanes: '50'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet21:
      admin_status: up
      alias: Eth22/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '22'
      lanes: '49'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet22:
      admin_status: up
      alias: Eth23/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '23'
      lanes: '52'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet23:
      admin_status: up
      alias: Eth24/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '24'
      lanes: '51'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet24:
      admin_status: up
      alias: Eth25/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '25'
      lanes: '2'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet25:
      admin_status: up
      alias: Eth26/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '26'
      lanes: '1'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet26:
      admin_status: up
      alias: Eth27/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '27'
      lanes: '4'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet27:
      admin_status: up
      alias: Eth28/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '28'
      lanes: '3'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet28:
      admin_status: up
      alias: Eth29/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '29'
      lanes: '6'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet29:
      admin_status: up
      alias: Eth30/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '30'
      lanes: '5'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet30:
      admin_status: up
      alias: Eth31/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '31'
      lanes: '8'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet31:
      admin_status: up
      alias: Eth32/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '32'
      lanes: '7'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet32:
      admin_status: up
      alias: Eth33/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '33'
      lanes: '10'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet33:
      admin_status: up
      alias: Eth34/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '34'
      lanes: '9'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet34:
      admin_status: up
      alias: Eth35/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '35'
      lanes: '12'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet35:
      admin_status: up
      alias: Eth36/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '36'
      lanes: '11'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet36:
      admin_status: up
      alias: Eth37/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '37'
      lanes: '14'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet37:
      admin_status: up
      alias: Eth38/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '38'
      lanes: '13'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet38:
      admin_status: up
      alias: Eth39/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '39'
      lanes: '16'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet39:
      admin_status: up
      alias: Eth40/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '40'
      lanes: '15'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet40:
      admin_status: up
      alias: Eth41/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '41'
      lanes: '18'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet41:
      admin_status: up
      alias: Eth42/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '42'
      lanes: '17'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet42:
      admin_status: up
      alias: Eth43/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '43'
      lanes: '20'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet43:
      admin_status: up
      alias: Eth44/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '44'
      lanes: '19'
      mtu: '1500'
      speed: '1000'
      subport: '0'
    Ethernet44:
      admin_status: up
      alias: Eth45/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '45'
      lanes: '22'
      mtu: '1500'
      speed: '1000'
      subport: '0'
      description: 'controller with oob'
    Ethernet45:
      admin_status: up
      alias: Eth46/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '46'
      lanes: '21'
      mtu: '1500'
      speed: '1000'
      subport: '0'
      description: 'controller with oob'
    Ethernet46:
      admin_status: up
      alias: Eth47/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '47'
      lanes: '24'
      mtu: '1500'
      speed: '1000'
      subport: '0'
      description: 'chassis oob'
    Ethernet47:
      admin_status: up
      alias: Eth48/1
      autoneg: 'on'
      dhcp_rate_limit: '300'
      fec: none
      index: '48'
      lanes: '23'
      mtu: '1500'
      speed: '1000'
      subport: '0'
      description: 'uplink'
    Ethernet48:
      admin_status: up
      alias: Eth49/1
      autoneg: 'off'
      dhcp_rate_limit: '300'
      fec: none
      index: '49'
      lanes: '60'
      mtu: '1500'
      speed: '10000'
      subport: '0'
    Ethernet49:
      admin_status: up
      alias: Eth50/1
      autoneg: 'off'
      dhcp_rate_limit: '300'
      fec: none
      index: '50'
      lanes: '58'
      mtu: '1500'
      speed: '10000'
      subport: '0'
    Ethernet50:
      admin_status: up
      alias: Eth51/1
      autoneg: 'off'
      dhcp_rate_limit: '300'
      fec: none
      index: '51'
      lanes: '59'
      mtu: '1500'
      speed: '10000'
      subport: '0'
    Ethernet51:
      admin_status: up
      alias: Eth52/1
      autoneg: 'off'
      dhcp_rate_limit: '300'
      fec: none
      index: '52'
      lanes: '57'
      mtu: '1500'
      speed: '10000'
      subport: '0'
    Ethernet52:
      admin_status: up
      alias: Eth53/1
      autoneg: 'off'
      dhcp_rate_limit: '300'
      fec: none
      index: '53'
      lanes: '62'
      mtu: '1500'
      speed: '10000'
      subport: '0'
    Ethernet53:
      admin_status: up
      alias: Eth54/1
      autoneg: 'off'
      dhcp_rate_limit: '300'
      fec: none
      index: '54'
      lanes: '64'
      mtu: '1500'
      speed: '10000'
      subport: '0'
    Ethernet54:
      admin_status: up
      alias: Eth55/1
      autoneg: 'off'
      dhcp_rate_limit: '300'
      fec: none
      index: '55'
      lanes: '61'
      mtu: '1500'
      speed: '10000'
      subport: '0'
    Ethernet55:
      admin_status: up
      alias: Eth56/1
      autoneg: 'off'
      dhcp_rate_limit: '300'
      fec: none
      index: '56'
      lanes: '63'
      mtu: '1500'
      speed: '10000'
      subport: '0'
  VLAN:
    "Vlan%{hiera('netcfg_ib_vlan')}":
      vlanid: "%{hiera('netcfg_ib_vlan')}"
    "Vlan%{hiera('netcfg_oob_vlan')}":
      vlanid: "%{hiera('netcfg_oob_vlan')}"
  VLAN_MEMBER:
    # ib mgmt
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet0":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet1":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet2":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet3":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet4":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet5":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet6":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet7":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet8":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet9":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet10":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet11":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet12":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet13":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet14":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet15":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet16":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet17":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet18":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet19":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet20":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet21":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet22":
      tagging_mode: untagged
    # oob mgmt
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet23":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet24":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet25":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet26":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet27":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet28":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet29":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet30":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet31":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet32":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet33":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet34":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet35":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet36":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet37":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet38":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet39":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet40":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet41":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet42":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet43":
      tagging_mode: untagged
    # trunk
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet44":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet44":
      tagging_mode: tagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet45":
      tagging_mode: untagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet45":
      tagging_mode: tagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet46":
      tagging_mode: tagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet46":
      tagging_mode: tagged
    "Vlan%{hiera('netcfg_ib_vlan')}|Ethernet47":
      tagging_mode: tagged
    "Vlan%{hiera('netcfg_oob_vlan')}|Ethernet47":
      tagging_mode: tagged
