---
# Ensure that the BOSS device is the first device
profile::base::physical::load_ahci_first: true
profile::base::physical::load_ahci_first_scsidrv: 'megaraid_sas'

#FIXME:el9 move to common after all computes are el9 with zed
openstack_version: "zed"

#FIXME: should not be needed here!
nova::compute::libvirt::cpu_models:              ['EPYC']
