---
profile::openstack::skyline::allow_from_network:
  - '0.0.0.0/0'     # Allow skyline from everywhere

profile::openstack::skyline::allow_from_network6:
  - '::/0'          # Allow skyline from everywhere

profile::openstack::skyline::manage_firewall6: true

profile::openstack::skyline::server_name: "%{hiera('public__address__skyline_bgo')}"
profile::openstack::skyline::ssl_cert:    "/etc/pki/tls/certs/%{hiera('public__address__skyline_bgo')}.cert.pem"
profile::openstack::skyline::ssl_key:     "/etc/pki/tls/private/%{hiera('public__address__skyline_bgo')}.key.pem"
